CREATE TABLE Countries (
    CountryCode CHARACTER (2) PRIMARY KEY,
    CountryName CHARACTER (70) NOT NULL
    );

CREATE TABLE Rooms (
    RoomID INTEGER (2) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    RoomName CHARACTER (150) NOT NULL,
	Country CHARACTER (150) NOT NULL,
    LightOn BIT DEFAULT 0 NOT NULL   
    );